### ISSUE TITLE
Sorry I'm bad at this but what's this error

### ISSUE THREAD

**Issue by Trolna** [Quenty/ROBLOX-group-autoranker#3]
I can't do js or json only lua lol
what the hell is this
xd
`Error: Cannot find module 'object-assign'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Dom\Desktop\ROBLOX-group-autoranker-master\server.js:1:82)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)`
how 2 fix?

**Comment by Quenty** [comment]
You may have to run `npm install` 

This project may need to be updated to work. It's not maintained very well right now.

**Comment by Trolna** [comment]
K, thanks
